[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/privacy"
  to = "/privacy-tr.html"
  status = 302

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-tr.html"
  status = 302

[[redirects]]
  from = "/en/privacy"
  to = "/privacy-en.html"
  status = 302

[[redirects]]
  from = "/terms"
  to = "/terms-tr.html"
  status = 302

[[redirects]]
  from = "/en/terms"
  to = "/terms-en.html"
  status = 302

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "staging" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
